
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jul 01 21:28:46 GMT-03:00 2025
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FUNCTION = 11;
  public static final int Coma = 20;
  public static final int Diferente = 26;
  public static final int REPEAT = 4;
  public static final int INT = 13;
  public static final int ARRAY = 15;
  public static final int Menor = 23;
  public static final int FIN = 3;
  public static final int FOR = 10;
  public static final int Mayor_Igual = 28;
  public static final int AND = 34;
  public static final int Mayor = 24;
  public static final int INI = 2;
  public static final int PuntoYComa = 21;
  public static final int OR = 35;
  public static final int Division = 32;
  public static final int Menor_Igual = 27;
  public static final int Modulo = 33;
  public static final int LANG = 14;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int Llave_Apertura = 16;
  public static final int Llave_Cierre = 17;
  public static final int error = 1;
  public static final int CHECK = 5;
  public static final int ERROR = 38;
  public static final int ELSE = 8;
  public static final int WHILE = 9;
  public static final int Parentesis_C = 19;
  public static final int Identificador = 36;
  public static final int Parentesis_A = 18;
  public static final int Resta = 30;
  public static final int Igual_Comparacion = 25;
  public static final int Multiplicacion = 31;
  public static final int Numero = 37;
  public static final int INTER = 6;
  public static final int Suma = 29;
  public static final int Igual = 22;
  public static final int PRINT = 7;
}

